# Site settings
title: My Journey Blog
email: mrvines94@gmail.com
description: Thoughts As I Move Towards The Unknown
baseurl: "/personal-blog"
twitter_username: The_Nerdistry
avatar: "img/Beau headshot.jpg" # Set footer avatar
paginate: 3

# Build settings
markdown: kramdown
permalink: /:title

# Default Settings
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      author: "Jason Vines" # Set default author name
      categories: "thoughts"
      layout: "post"
      comments: true
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
